### ISSUE TITLE
MongoStore.create({}) options 'client' and 'clientPromise' not compatible with Mongoose version 6

### ISSUE THREAD

**Issue by bradenmitchell** [jdesboeufs/connect-mongo#436]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Mongoose has been updated to version 6. When using `client` or `clientPromise` in `MongoStore.create({  })`, sessions are no longer saved to database.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by rfox12** [comment]
Can you provide any information that this is a bug in `connect-mongo` and not `mongoose`?  I don't use `mongoose` (I really don't see the advantages over the core `mongodb` driver); and I (among many others) have been using `connect-mongo` reliably in production.

**Comment by rfox12** [comment]
This will probably be solved with my PR that I'm trying to finish out

**Comment by SavarJ** [comment]
Hi. Any update? Everyone I know uses mongoose for MongoDB and when I do 
`store: MongoStore.create({
      client: mongoose.connection,
      dbName: "sessions",
    }`
it gives me an error of `TypeError: con.db is not a function`

**Comment by mingchuno** [comment]
4.6.0 released

**Comment by mq1n** [comment]
It's still happening for me on 4.6.0

`TypeError: con.db is not a function
    at ...\node_modules\connect-mongo\build\main\lib\MongoStore.js:126:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

**Comment by gkostov** [comment]
This example demonstrates how it's done with Mongoose 6 https://github.com/jdesboeufs/connect-mongo/blob/master/example/mongoose.js . Though I prefer a bit simpler approach (one that's also closer to what was there with previous versions):

```javascript
...
store: MongoStore.create({
    client: mongoose.connection.getClient(),
...
```

**Comment by vishwajeetsinh-arham** [comment]
`const store = MongoStore.create({
    mongoUrl: dbUrl,
    secret: 'thisshouldbeabettersecret',
    touchAfter: 24 * 60 * 60
})`

**Comment by gkostov** [comment]
@vishwajeetsinh-arham , your code (the `mongoUrl` option) tells `connect-mongo` to create and use its own connection to Mongo and will not reuse an existing one (like one created with Mongoose). It may not be a big deal in most cases but, being constrained by available memory, I prefer to keep the number of connections to a minimum.

**Comment by rnher** [comment]
Please using for mongo-store options   { client : mongoose.connection.getClient() )
